version: "3.9"

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "8080:8080"

  client1:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: client1
    depends_on:
      - proxy

  client2:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: client2
    depends_on:
      - proxy
